### ISSUE TITLE
Nightmare_tyxml: unnecessary complexity of `XXX_of`.

### ISSUE THREAD

**Issue by xhtmlboi** [funkywork/nightmare#17]
At the moment, the construction of a tag taking an endpoint seems to me too heavily complex. You have to repeat tags taking `src`, `href` and co, whereas it would be enough to do `a_href_of endpoint continuation` and `a_src_of endpoint continuation` and not have to reproduce each tag.

**Comment by gr-im** [comment]
In many cases your approach works, but unfortunately not for cases where it is necessary to generate two attributes. For example, `form` where the method, in addition to the action, is induced by the type of the `endpoint`.
Producing a list of attributes would be quite annoying because it would force you to write the form call in this way: 

```ocaml
Tyxml.Html.form ~a:(a_method_of endpoint :: a_action_of endpoint continuation :: []) []
(* Or supposing that [a_method_of] returns a list of attrib including the method. *)
Tyxml.Html.form ~a:(method_of enpoint @ []) []
```
Both suggestion seems heavy on the user-space.

**Comment by gr-im** [comment]
ping @xhtmlboi

**Comment by xhtmlboi** [comment]
That's fine for now :) and as the hardest (and most boring) part has been done by @xvw, I'll close the exit.
